# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test
      
      - persist_to_workspace:
          root: /tmp/workspace
          paths: build

  deploy:
    requires:
      - build
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Set CI user
          command: |
            git config user.email "ci-build@brick-breaker.net"
            git config user.name "ci-build"
      - deploy: npm run deploy
    filters:
      branches:
        only: master
