# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test

      - run: npm run build
      - run: pwd
      - run: ls
      - run:
          name: Set CI user
          command: |
            git config user.email "ci-build@brick-breaker.net"
            git config user.name "ci-build"
      - run: npm run deploy
      
      - persist_to_workspace:
          root: ./
          paths:
            - build
            - node_modules

  deploy:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Set CI user
          command: |
            npm install gh-pages@2.0.1
            git config user.email "ci-build@brick-breaker.net"
            git config user.name "ci-build"
      - run: pwd
      - run: ls
      - run: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
        requires:
          - build
        filters:
          branches:
            only: master