# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1

    # working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test

      # - run: npm run build
      - run: npm run x
      
      - persist_to_workspace:
          root: ./
          paths:
            - build
            - node_modules

  gh-deploy:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Set CI user
          command: |
            git config user.email "ci-build@brick-breaker.net"
            git config user.name "ci-build"
      - run: npm run deploy
  
  s3-deploy:
    name: 'Deploy build to s3 staging bucket'
    docker:
        - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync build s3://brick-breaker-staging/${CIRCLE_BRANCH} --delete
  
  s3-clean:
    name: 'Remove merged (or deleted) branches deployments'
    docker:
        - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: List active deployments
          command: aws s3 ls s3://brick-breaker-staging/feature/ | sed 's/^ *PRE //' >> deployments.txt
      - run:
          name: List active branches # TODO: remove branches with no activity in a month
          command: git branch -r | grep feature | sed 's/origin\/feature\///' >> branches.txt
      - run:
          name: List deployments with no active branch
          command: comm -23 deployments.txt branches.txt >> old-deployments.txt
      - run:
          name: Remove deployments with no active branch
          command: while read in; aws s3 rm s3://brick-breaker-staging/feature/$in --recursive --dry-run; done < old-deployments.txt

workflows:
  version: 2
  build:
    jobs:
      # - build
      - s3-clean
      # - gh-deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master
      # - s3-deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: /feature\/.*/